config/routes.rb
Rails.application.routes.draw do
  root 'quotes#index'
  resources :quotes
  get 'about', to: 'quotes#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
  validates :saying, presence: true, length: {maximum: 140, minimum: 3}
  validates :author, presence: true, length: {maximum: 50, minimum: 3}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quote = Quote.order("RANDOM()").first
  end

  def create
    @quote = Quote.create(quote_params)
    if @quote.invalid?
      flash[:error] = '<strong>Could not save</strong> the data you entered is invalid.'
    end
    redirect_to root_path
  end

  private

  def quote_params
    params.require(:quote).permit(:saying, :author)
  end

  def about
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Splurty</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class ="row">
      <div class="col-3">
        <%= link_to root_path, class: 'logo' do %>
          <div class="circle">
            <br />
            FINANCIAL
            <br />
            FREEDOM
            <br />
            FOR LIFE
          </div>
        <% end %>
      </div>

      <div class="col col-sm-4 hidden-xs-down slogan">
        Splurting out unsolicated advice about financial freedom since 2019
      </div>

      <div class="col-10 offset-1 offset-sm-0 col-sm-5 links">
        <!-- Button trigger modal -->
        <%= link_to 'Contribute', '#', data: {toggle: 'modal', target: '#myModal'} %>
        &nbsp;&nbsp;
        <%= link_to 'About', about_path %>
      </div>

    </header>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title" id="myModalLabel">Contribute Your Quote</h4>
          </div>
          <%= simple_form_for Quote.new do |f| %>
            <div class="modal-body">
              <%= f.input :saying, label: "Enter the saying you would like to add", placeholder: "Every moment is a fresh beginning." %>
              <br />
              <%= f.input :author, label: "Enter the author of this saying", placeholder: "T.S. Eliot"%>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= f.submit 'Create', class: 'btn btn-success' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <hr />
    
    <br class="clear" />

    <div class="container"> 
      <% if flash[:error].present? %>
        <div class="col-10 offset-1 alert alert-danger">
          <%= flash[:error].html_safe %>
        </div>
      <% end %>
      <%= yield %>
    </div>

    <div class="footer">
      <div class="container">
        <div class="row">
          <div class="col-12 col-sm-6">
            <%= link_to "This isn't enough, I need more", root_path, class: 'next-quote' %>
          </div>
          <div class="col-12 col-sm-6 footer-blurb">
            Proudly hacked by <a href="https://determined-bassi-314336.netlify.com"> Ivan Perez </a> <br />
          </div>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/quotes/about.html.erb
<div class="col-10 offset-1 about">
  <h1>About Splurty</h1>
  <p> 
    Splurty was built by <a target="_blank" href="https://determined-bassi-314336.netlify.com"> Ivan</a>. A civil engineer turned web developer.
  </p>
  <br />
  <p>
    Taking his knowledge of project management and project engineering to promote efficiency in the development of web applications. 
  </p>

  <div class="row">
    <div class="col-12 col-sm-4">
      <%= image_tag 'me.jpg', class: 'img-fluid' %>
    </div>
    <div class="col-12 col-sm-7 offset-sm-1">
      <h2 class="text-center"> Ivan Perez</h2>
      <br />
      <p>
        Ivan Perez has begun his journey into the world of web development. Enrolled in the UC Berkeley Coding Bootcamp, he has begun working with Ruby, CSS, HTML, and Ruby On Rails. His goal is to obtain employment at a large tech company to put his new skills to the test.
      </p>
    </div>
  </div>
</div>

<br class="clear" />
<br />
<br />
<br />
<br />

app/views/quotes/index.html.erb
<h2>
  <span> SPLURTY / No. <%= @quote.id %></span>
  Here's the <u>best advice about financial freedom</u> you can get!
</h2>

<br class="clear">
<br />
<br />
<br />

<h1><%= @quote.saying %></h1>
<h2 class="float-right">- <%= @quote.author %></h2>

<br />
<br />
<br />